### ISSUE TITLE
バックエンドを指定すべきところでターゲットが指定されている

### ISSUE THREAD

**Issue by atinfinity** [Ar-Ray-code/opencv_dnn_example#1]
<https://github.com/Ar-Ray-code/opencv_dnn_example/tree/af81efe7e44e327f183747dcf95b5d2c711cdefa>時点のコードを読みました。以下のコードにてdnnモジュールにおけるターゲット、バックエンドが混同されているのか、バックエンドを指定すべきところでターゲットが指定されているように見受けられます。

- <https://github.com/Ar-Ray-code/opencv_dnn_example/blob/af81efe7e44e327f183747dcf95b5d2c711cdefa/cpp/yolo_cvdnn.cpp#L31>
- <https://github.com/Ar-Ray-code/opencv_dnn_example/blob/af81efe7e44e327f183747dcf95b5d2c711cdefa/cpp/yolo_cvdnn_image.cpp#L28>
- <https://github.com/Ar-Ray-code/opencv_dnn_example/blob/af81efe7e44e327f183747dcf95b5d2c711cdefa/py/yolo_cvdnn_image.py#L17>
- <https://github.com/Ar-Ray-code/opencv_dnn_example/blob/af81efe7e44e327f183747dcf95b5d2c711cdefa/py/yolo_cvdnn_webcam.py#L17-L20>

バックエンドの指定は以下のenum値を用いるべきだと思われます。  
<https://docs.opencv.org/4.5.3/d6/d0f/group__dnn.html#ga186f7d9bfacac8b0ff2e26e2eab02625>

併せてこちらの記事にも同様の問題が含まれています。  
<https://ar-ray.hatenablog.com/entry/2021/05/31/180000>

**Comment by Ar-Ray-code** [comment]
記事およびソースコードをご覧いただき、そしてご指摘ありがとうございます。
このソースコードはNCSの環境構築の確認用に作成したプログラムの確認用に作成していましたが、条件によってバウンディングボックスのずれがあったと思います。

記事およびソースコードの修正次第、また連絡させていただきます。

**Comment by Ar-Ray-code** [comment]
変更しました（gist上のプログラムを変更してブログのURLも変更しました）

https://gist.github.com/Ar-Ray-code/b07012e047883fbe7dd50dfe55c7f531/revisions#diff-8b409573a845d5bc51f45b208cb03ad9fa8735963d83ebdc1feb40f4284531bb

**Comment by atinfinity** [comment]
@Ar-Ray-code <https://docs.opencv.org/4.5.3/d6/d0f/group__dnn.html#ga186f7d9bfacac8b0ff2e26e2eab02625>に

> DNN_BACKEND_DEFAULT equals to DNN_BACKEND_INFERENCE_ENGINE if OpenCV is built with Intel's Inference Engine library or DNN_BACKEND_OPENCV otherwise.

という記載があります。Intel Inference Engineを有効にしたOpenCVを使用する場合、`DNN_BACKEND_DEFAULT`は`DNN_BACKEND_INFERENCE_ENGINE`と等価になります。そのため、

```python
 # CPU 
 net.setPreferableBackend(cv2.dnn.DNN_BACKEND_DEFAULT) 
 net.setPreferableTarget(cv2.dnn.DNN_TARGET_CPU) 
```

の「CPU」というのがIntel Inference Engineを使わないOpenCV内部のCPU実装を呼ぶことを期待しているとしたらsetPreferableBackendで`cv2.dnn.DNN_BACKEND_OPENCV`を指定するのが適切です。

**Comment by Ar-Ray-code** [comment]
CPU使用時では`cv2.dnn.DNN_BACKEND_OPENCV`のほうがパフォーマンスが良かったように感じたので[リファレンス](https://docs.opencv.org/4.5.4/db/d30/classcv_1_1dnn_1_1Net.html#a9dddbefbc7f3defbe3eeb5dc3d3483f4)に従って変更しました。ありがとうございます。

<https://github.com/Ar-Ray-code/opencv_dnn_example/commit/02484babb7ddd90a71df0fee1666de011ad25926>
